server {
  listen 80;
  server_name localhost;
client_max_body_size 20m;
  # ==========================================
  # 1. 前端 Angular 靜態檔案
  # ==========================================
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html; # 支援 Angular SPA 路由 fallback
  }

  # ==========================================
  # 2. 後端 HTTP API 代理
  # ==========================================
  location /api/ {
    # 透過 host.docker.internal 直接連回你這台電腦的後端 Port 8081
    proxy_pass http://backend-api:8081/;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # ==========================================
  # 3. 后端 WebSocket 代理（新加入）
  # ==========================================
  location /ws {
    proxy_pass http://backend-api:8081; # 轉發給 Java WebSocket

    # 關鍵：必須加上這三行，Nginx 才能支援 WebSocket 協定升級與握手
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
    # ==========================================
  # 3. 后端 w圖片 代理（新加入）
  # ==========================================
    location /uploads/ {
    proxy_pass http://backend-api:8081/uploads/;
}
}
