server {
  listen 80;
  server_name localhost;

  # =====================
  # 前端 Angular
  # =====================
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  # =====================
  # 後端 API（關鍵）
  # =====================
  location /api/ {
    proxy_pass https://labels-biz-sheep-concerning.trycloudflare.com;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
